# Generated by Django 5.1.5 on 2025-02-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('views', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
