# Generated by Django 5.1.5 on 2025-02-24 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='youtubevideo',
            table='youtube_video',
        ),
    ]
